[build]
  command = "yarn build"
  publish = "dist"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Handle other errors
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 500 