// src/pages/generated-playlist-screen/components/ActionButtons.jsx
import React, { useState } from "react";
import Icon from "../../../components/AppIcon";
import { createPlaylist, addTracksToPlaylist } from "../../../services/spotify";
import { useNavigate } from "react-router-dom";

const ActionButtons = ({ playlist, onSave, onCreateAnother }) => {
  const [isSaving, setIsSaving] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [saveError, setSaveError] = useState(null);

  const navigate = useNavigate();

  const handleSave = async () => {
    try {
      setIsSaving(true);
      setSaveError(null);
      setSaveSuccess(false);

      // Create the playlist
      const newPlaylist = await createPlaylist(
        playlist.name,
        playlist.description || "Generated by AI Playlist Creator"
      );

      // Add tracks to the playlist
      const trackUris = playlist.tracks.map((track) => track.uri);
      await addTracksToPlaylist(newPlaylist.id, trackUris);

      setSaveSuccess(true);
      // Auto-hide success message after 3 seconds
      setTimeout(() => setSaveSuccess(false), 3000);
    } catch (error) {
      console.error("Save error:", error);
      setSaveError(error.message || "Failed to save playlist");
      // Auto-hide error message after 5 seconds
      setTimeout(() => setSaveError(null), 5000);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="space-y-4">
      {/* Status Messages */}
      {saveSuccess && (
        <div className="bg-green-500 bg-opacity-10 border border-green-500 border-opacity-20 rounded-lg p-4">
          <div className="flex items-center gap-3">
            <div className="w-6 h-6 bg-green-500 bg-opacity-20 rounded-full flex items-center justify-center">
              <Icon name="Check" size={14} className="text-green-500" />
            </div>
            <p className="text-green-500 font-medium">
              Playlist saved to your Spotify account and history!
            </p>
          </div>
        </div>
      )}

      {saveError && (
        <div className="bg-red-500 bg-opacity-10 border border-red-500 border-opacity-20 rounded-lg p-4">
          <div className="flex items-center gap-3">
            <div className="w-6 h-6 bg-red-500 bg-opacity-20 rounded-full flex items-center justify-center">
              <Icon name="AlertCircle" size={14} className="text-red-500" />
            </div>
            <p className="text-red-500 font-medium">{saveError}</p>
          </div>
        </div>
      )}

      {/* Action Buttons */}
      <div className="bg-surface bg-opacity-70 backdrop-blur-md border border-border border-opacity-20 rounded-xl p-6">
        <div className="grid grid-cols-1 sm:grid-cols-3 lg:grid-cols-3 gap-6">
          {/* Save to Spotify */}
          <div className="space-y-2">
            <button
              onClick={handleSave}
              disabled={isSaving || saveSuccess}
              className={`w-full flex items-center justify-center gap-3 px-6 py-3 rounded-lg font-medium transition-all duration-200 ${
                saveSuccess
                  ? "bg-green-500 text-white cursor-default"
                  : isSaving
                  ? "bg-surface border border-border text-text-secondary cursor-not-allowed"
                  : "bg-primary hover:bg-primary-hover text-white shadow-lg hover:shadow-xl transform hover:scale-105"
              }`}
            >
              {isSaving ? (
                <>
                  <div className="w-4 h-4 border-2 border-text-secondary border-t-transparent rounded-full animate-spin" />
                  <span>Saving...</span>
                </>
              ) : saveSuccess ? (
                <>
                  <Icon name="Check" size={18} />
                  <span>Saved!</span>
                </>
              ) : (
                <>
                  <Icon name="Save" size={18} />
                  <span>Save to Spotify</span>
                </>
              )}
            </button>
            <p className="text-xs text-text-disabled text-center">
              Save this AI-generated playlist to your Spotify library and
              history
            </p>
          </div>

          {/* Create Another */}
          <div className="space-y-2">
            <button
              onClick={onCreateAnother}
              className="w-full flex items-center justify-center gap-3 px-6 py-3 bg-surface border border-border hover:bg-surface-hover text-text-primary rounded-lg font-medium transition-all duration-200"
            >
              <Icon name="Plus" size={18} />
              <span>Create Another</span>
            </button>
            <p className="text-xs text-text-disabled text-center">
              Start over and create another playlist
            </p>
          </div>

          {/* View History */}
          <div className="space-y-2">
            <button
              onClick={() => navigate("/history")}
              className="w-full flex items-center justify-center gap-3 px-6 py-3 bg-surface border border-border hover:bg-surface-hover text-text-primary rounded-lg font-medium transition-all duration-200"
            >
              <Icon name="History" size={18} />
              <span>View History</span>
            </button>
            <p className="text-xs text-text-disabled text-center">
              View your saved playlist history
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ActionButtons;
